server:
  port: 8085

spring:
  application:
    name: reporting-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

services:
  task-service-url: http://task-service
  time-tracking-service-url: http://time-tracking-service
  project-service-url: http://project-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
